<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_AjaxLayer
 */
?>
<?php if ($block->canShowBlock()) : ?>
    <?php
    $helper = $this->helper(\Magerubik\AjaxLayer\Helper\Data::class);
    $filters = $block->getFilters();
    $layerConfig = $helper->getLayerConfiguration($filters);
    $filtered = count($block->getLayer()->getState()->getFilters());
    ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <div id="ln_overlay" class="mr_overlay">
			<div class="double-bounce-spinner">
				<div class="double-bounce1"></div>
				<div class="double-bounce2"></div>
			</div>
        </div>
        <div class="block-title filter-title" data-count="<?= /** @noEscape */ $filtered ?>">
            <strong data-role="title"><?= /** @noEscape */ __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= /** @noEscape */ $block->getChildHtml('state') ?>
            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /** @noEscape */ $block->getClearUrl() ?>" class="action clear filter-clear">
                        <span><?= /** @noEscape */ __('Clear All') ?></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($filters as $key => $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                            <?= /** @noEscape */ __('Shopping Options') ?>
                        </strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content">
                        <?php $wrapOptions = true;
                    endif; ?>
                    <div data-role="ln_collapsible" class="filter-options-item"
                         attribute="<?= /** @noEscape */ $filter->getRequestVar() ?>">
                        <div data-role="ln_title" class="filter-options-title"><?= /** @noEscape */ __($filter->getName()) ?></div>
                        <div data-role="ln_content" class="filter-options-content">
                            <?= /** @noEscape */ $block->getChildBlock('renderer')->setFilter($filter)->render($filter); ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </div>
            <?php else : ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
            <?php endif; ?>
            <?php if ($helper->ajaxEnabled()) : ?>
            <script type="text/x-magento-init">
                {
                     ".block-content.filter-content":{
                         "mrAjax": <?= /** @noEscape */ $layerConfig ?>
                     }
                }
            </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
